services:
  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - myapp-net
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      #- ./mysql_data:/var/lib/mysql

  rest-api-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - myapp-net
    depends_on:
      - mysql_db

networks:
  myapp-net:
    driver: bridge
volumes:
  mysql_data:

